## ECE2112_PA3

Made by: Geri Allison Geneta | 2ECE-B

This repository contains our Programming Assignment 3 for ECE2112. This project covers three python problems referenced to Module 3 - Pandas.

In [ ]:
import pandas as pd

## A. POSITIONAL AND LABEL-BASED SLICING

The following problem uses the cars dataset and demonstrates how to select specific rows and columns using positional-based and label-based indexing in Pandas.

The following functions and methods were used in this problem:

* pd.read_csv() - a Pandas function used to read a CSV file and load its contents into a DataFrame. Here, it is used to import the cars.csv dataset into a DataFrame named cars.

* .iloc[] - a Pandas indexing method used to select rows and columns based on their integer positions. In this problem, cars.iloc[6:11] selects the rows starting from index 6 up to, but not including, index 11.

* .loc[] - a Pandas indexing method used to select data based on row and column labels. In this problem, cars_6_to_10.loc[:, ['Model', 'mpg', 'cyl', 'hp', 'gear']] selects all rows from the previously sliced DataFrame while keeping only the specified columns.

These methods were combined to first select a specific range of rows using .iloc[], and then select specific columns using .loc[]. The resulting data contains the cars from index 6 to index 10 and only the Model, mpg, cyl, hp, and gear information.

In [ ]:
cars = pd.read_csv('cars.csv')
cars

,Model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [ ]:
cars_6_to_10 = cars.iloc[6:11]
cars_6_to_10

         Model   mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  carb
6   Duster 360  14.3    8  360.0  245  3.21  3.57  15.84   0   0     3     4
7    Merc 240D  24.4    4  146.7   62  3.69  3.19  20.00   1   0     4     2
8     Merc 230  22.8    4  140.8   95  3.92  3.15  22.90   1   0     4     2
9     Merc 280  19.2    6  167.6  123  3.92  3.44  18.30   1   0     4     4
10   Merc 280C  17.8    6  167.6  123  3.92  3.44  18.90   1   0     4     4

In [ ]:
cars_6_to_10.loc[:, ['Model', 'mpg', 'cyl', 'hp', 'gear']]

         Model   mpg  cyl   hp  gear
6   Duster 360  14.3    8  245     3
7    Merc 240D  24.4    4   62     4
8     Merc 230  22.8    4   95     4
9     Merc 280  19.2    6  123     4
10   Merc 280C  17.8    6  123     4

## B. MODEL LOOKUP

The following problem uses the cars dataset to look up specific car models and display their corresponding information.

The following functions and methods were used in this problem:

* Boolean Indexing - a method used to filter rows in a DataFrame by creating a condition that evaluates to either True or False. In this problem, cars['Model'] == 'Toyota Corolla' checks which row has the Model value equal to "Toyota Corolla".

* .loc[] - a Pandas indexing method used to select specific rows and columns based on labels. Here, it is used to find the row where the Model is "Pontiac Firebird" and display only the Model, mpg, hp, and wt columns.

These operations were combined to search for a specific car model and retrieve only the information needed from the dataset. The Toyota Corolla lookup returns its complete row, while the Pontiac Firebird lookup limits the output to the Model, mpg, hp, and wt columns.

In [ ]:
cars[cars['Model'] == 'Toyota Corolla']

             Model   mpg  cyl  disp  hp  drat     wt  qsec  vs  am  gear  carb
19  Toyota Corolla  33.9    4  71.1  65  4.22  1.835  19.9   1   1     4     1

In [ ]:
cars.loc[(cars['Model']) == 'Pontiac Firebird', ['Model', 'mpg', 'hp', 'wt']]

               Model   mpg   hp     wt
24  Pontiac Firebird  19.2  175  3.845

## C. MULTI-MODEL SUBSETTING

The following problem creates a smaller DataFrame from the cars dataset by selecting specific columns and then filtering the dataset to include only selected car models.

The following functions and methods were used in this problem:

* pd.DataFrame() - a Pandas function used to create a DataFrame. In this problem, it is used to create a new DataFrame containing only the Model, mpg, cyl, hp, and gear columns from the original cars DataFrame.

* .loc[] - a Pandas indexing method used to select specific rows and columns based on labels. Here, it is used to filter the car models while also selecting the required columns.

* Boolean OR operator | - an operator used to combine multiple filtering conditions. It allows the DataFrame to include a row when at least one of the conditions is True.

* .shape - a DataFrame attribute used to determine the number of rows and columns in a DataFrame. It returns the result in the form (rows, columns).

These operations were combined to create a subset containing only the Datsun 710, Lotus Europa, and Ferrari Dino models, together with their Model, mpg, cyl, hp, and gear information. The resulting DataFrame contains 3 rows and 5 columns, which is confirmed by using .shape.

In [ ]:
selected_cars = pd.DataFrame(cars, columns = ['Model', 'mpg','cyl', 'hp', 'gear'])
selected_cars

                  Model   mpg  cyl   hp  gear
0             Mazda RX4  21.0    6  110     4
1         Mazda RX4 Wag  21.0    6  110     4
2            Datsun 710  22.8    4   93     4
3        Hornet 4 Drive  21.4    6  110     3
4     Hornet Sportabout  18.7    8  175     3
5               Valiant  18.1    6  105     3
6            Duster 360  14.3    8  245     3
7             Merc 240D  24.4    4   62     4
8              Merc 230  22.8    4   95     4
9              Merc 280  19.2    6  123     4
10            Merc 280C  17.8    6  123     4
11           Merc 450SE  16.4    8  180     3
12           Merc 450SL  17.3    8  180     3
13          Merc 450SLC  15.2    8  180     3
14   Cadillac Fleetwood  10.4    8  205     3
15  Lincoln Continental  10.4    8  215     3
16    Chrysler Imperial  14.7    8  230     3
17             Fiat 128  32.4    4   66     4
18          Honda Civic  30.4    4   52     4
19       Toyota Corolla  33.9    4   65     4
20        Toyota Corona  21.5    4   97     3
21     Dodge Challenger  15.5    8  150     3
22          AMC Javelin  15.2    8  150     3
23           Camaro Z28  13.3    8  245     3
24     Pontiac Firebird  19.2    8  175     3
25            Fiat X1-9  27.3    4   66     4
26        Porsche 914-2  26.0    4   91     5
27         Lotus Europa  30.4    4  113     5
28       Ford Pantera L  15.8    8  264     5
29         Ferrari Dino  19.7    6  175     5
30        Maserati Bora  15.0    8  335     5
31           Volvo 142E  21.4    4  109     4

In [ ]:
selected_cars = pd.DataFrame(cars.loc[(cars['Model'] == 'Datsun 710') | (cars['Model'] == 'Lotus Europa') | (cars['Model'] == 'Ferrari Dino'), ['Model', 'mpg', 'cyl', 'hp', 'gear']])
selected_cars

           Model   mpg  cyl   hp  gear
2     Datsun 710  22.8    4   93     4
27  Lotus Europa  30.4    4  113     5
29  Ferrari Dino  19.7    6  175     5

In [ ]:
selected_cars.shape

(3, 5)

The End.

## Thank you for reading!